"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Check, Film, ImageIcon, Loader2, Pencil, RefreshCw, ScrollText } from "lucide-react";
import { useState, useTransition } from "react";
import type { StoryboardPageData } from "@/lib/storyboard-data";
import { regenerateMissingFramesAction, regenerateStoryboardFrameAction, updateShotPromptAction, validateScenarioAction } from "@/app/projects/[projectId]/storyboard/actions";

const timecode = (ms: number) => `${Math.floor(ms / 60_000)}:${String(Math.floor((ms % 60_000) / 1000)).padStart(2, "0")}.${String(ms % 1000).padStart(3, "0")}`;
const statusLabels: Record<string, string> = { DRAFT: "Brouillon", GENERATING: "En préparation", READY: "À valider", VALIDATED: "Validé", SUPERSEDED: "Version précédente", FAILED: "Erreur" };

export default function StoryboardStudio({ data, modal = false }: { data: StoryboardPageData; modal?: boolean }) {
  const router = useRouter();
  const [tab, setTab] = useState<"scene" | "shots" | "sketches">("scene");
  const [editing, setEditing] = useState<string | null>(null);
  const [draftPrompt, setDraftPrompt] = useState("");
  const [message, setMessage] = useState("");
  const [isPending, startTransition] = useTransition();
  const route = (sceneId: string) => `/projects/${encodeURIComponent(data.projectId)}/storyboard/${encodeURIComponent(sceneId)}`;
  function run(task: () => Promise<unknown>, success: string) {
    setMessage("");
    startTransition(async () => { try { await task(); setMessage(success); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Action impossible."); } });
  }
  return <div className={modal ? "max-h-[92vh] overflow-y-auto" : ""}>
    <header className="border-b border-slate-800 px-5 py-5 sm:px-8">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-300">Studio scénario · version {data.version.number}</p><h1 className="mt-2 text-2xl font-black sm:text-4xl">{data.projectTitle}</h1><p className="mt-2 text-sm text-slate-400">Scène {data.scene.position} sur {data.sceneCount} · {timecode(data.scene.startMs)} → {timecode(data.scene.endMs)}</p></div>
        <span className="rounded-full border border-cyan-400/30 bg-cyan-950/30 px-3 py-2 text-sm font-bold text-cyan-100">{statusLabels[data.version.status] || data.version.status}</span>
      </div>
      <nav aria-label="Vues du scénario" className="mt-6 grid grid-cols-3 gap-2 rounded-2xl bg-slate-900 p-1">
        {([["scene", ScrollText, "Scène"], ["shots", Film, "Plans"], ["sketches", ImageIcon, "Croquis"]] as const).map(([value, Icon, label]) => <button key={value} type="button" onClick={() => setTab(value)} aria-pressed={tab === value} className={`flex items-center justify-center gap-2 rounded-xl px-3 py-3 font-bold ${tab === value ? "bg-cyan-300 text-slate-950" : "text-slate-300 hover:bg-slate-800"}`}><Icon size={18} /> {label}</button>)}
      </nav>
    </header>

    <div className="px-5 py-6 sm:px-8">
      {message ? <p role="status" className="mb-5 rounded-xl border border-cyan-400/30 bg-cyan-950/30 p-3 text-sm text-cyan-100">{message}</p> : null}
      {tab === "scene" ? <section aria-labelledby="scene-title"><h2 id="scene-title" className="text-3xl font-black">{data.scene.title}</h2><p className="mt-5 text-lg leading-8 text-slate-200">{data.scene.narrativeContent}</p><dl className="mt-8 grid gap-4 sm:grid-cols-2">{[["Arc émotionnel", data.scene.emotionalArc], ["Son et ambiance", data.scene.soundVibe], ["Position dans l'histoire", data.scene.contextualPosition], ["Rythme", data.scene.pacing], ["Transition sortante", data.scene.transitionOut]].map(([label, value]) => <div key={label} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><dt className="text-xs font-black uppercase tracking-wider text-cyan-300">{label}</dt><dd className="mt-2 text-slate-200">{value}</dd></div>)}</dl><h3 className="mt-8 font-black">Références visuelles</h3><div className="mt-3 flex flex-wrap gap-2">{data.references.map((reference) => <span key={reference.id} title={reference.description} className="rounded-full border border-slate-700 px-3 py-2 text-sm">{reference.kind === "CAST" ? "Personnage" : reference.kind === "LOCATION" ? "Lieu" : "Accessoire"} · {reference.name}</span>)}</div></section> : null}

      {tab === "shots" ? <section aria-label="Découpage technique" className="space-y-5">{data.shots.map((shot) => <article id={`shot-${shot.id}`} key={shot.id} className="rounded-3xl border border-slate-800 bg-slate-900/55 p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-black text-cyan-200">Plan {shot.position} · {((shot.endMs - shot.startMs) / 1000).toFixed(3)} s</h2><span className="font-mono text-xs text-slate-400">{timecode(shot.startMs)} → {timecode(shot.endMs)}</span></div><dl className="mt-5 space-y-4">{[["Fonction", shot.shotFunction], ["Image de départ", shot.startFrame], ["Action et caméra", shot.actionAndCamera], ["Dynamiques environnementales", shot.environmentalDynamics], ["Image de fin", shot.endFrame], ["Mouvement caméra", shot.cameraMovement]].map(([label, value]) => <div key={label}><dt className="text-xs font-black uppercase text-slate-500">{label}</dt><dd className="mt-1 leading-7 text-slate-200">{value}</dd></div>)}</dl><div className="mt-5 rounded-2xl border border-cyan-400/20 bg-slate-950 p-4"><p className="text-xs font-black uppercase text-cyan-300">Prompt Seedance</p>{editing === shot.id ? <><textarea aria-label={`Modifier le prompt du plan ${shot.position}`} value={draftPrompt} onChange={(event) => setDraftPrompt(event.target.value)} rows={6} className="mt-3 w-full rounded-xl border border-slate-700 bg-slate-900 p-3 text-sm" /><button type="button" disabled={isPending} onClick={() => startTransition(async () => { try { const result = await updateShotPromptAction(data.projectId, shot.id, draftPrompt); if (result.sceneId) router.push(route(result.sceneId)); } catch (error) { setMessage(error instanceof Error ? error.message : "Modification impossible."); } })} className="mt-3 rounded-xl bg-cyan-300 px-4 py-2 font-black text-slate-950">Enregistrer dans une nouvelle version</button></> : <p className="mt-2 text-sm leading-6 text-slate-300">{shot.seedancePrompt}</p>}</div><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={() => { setEditing(shot.id); setDraftPrompt(shot.seedancePrompt); }} className="inline-flex items-center gap-2 rounded-xl border border-slate-700 px-4 py-2 text-sm font-bold"><Pencil size={16} /> Modifier</button><button type="button" disabled={isPending} onClick={() => run(() => regenerateStoryboardFrameAction(data.projectId, shot.id), "Croquis préparé en mode test.")} className="inline-flex items-center gap-2 rounded-xl border border-slate-700 px-4 py-2 text-sm font-bold"><RefreshCw size={16} /> Régénérer ce plan</button></div></article>)}</section> : null}

      {tab === "sketches" ? <section aria-label="Croquis du storyboard"><p className="mb-5 rounded-2xl border border-amber-400/25 bg-amber-950/20 p-4 text-sm text-amber-100">Les croquis aident à comprendre la structure de l'histoire, mais ne représentent pas l'apparence exacte de la vidéo finale.</p><div className="grid gap-5 md:grid-cols-2">{data.shots.map((shot) => <button key={shot.id} type="button" onClick={() => { setTab("shots"); window.setTimeout(() => document.getElementById(`shot-${shot.id}`)?.focus(), 0); }} className="group overflow-hidden rounded-3xl border border-slate-800 bg-slate-900 text-left focus:outline-none focus:ring-2 focus:ring-cyan-300"><div className="relative aspect-[9/16] bg-gradient-to-br from-slate-800 to-cyan-950">{shot.storyboard?.available ? <Image src={`/api/storyboard-frames/${encodeURIComponent(shot.storyboard.id)}/image`} alt={`Croquis du plan ${shot.position} : ${shot.shotFunction}`} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover" unoptimized /> : <div className="absolute inset-0 grid place-items-center p-8 text-center text-slate-400"><ImageIcon className="mx-auto mb-3" /><span>{shot.storyboard?.status === "FAILED" ? "Croquis indisponible" : "Croquis à préparer"}</span></div>}<span className="absolute left-3 top-3 grid h-10 w-10 place-items-center rounded-full bg-slate-950/90 font-black text-cyan-200">{shot.position}</span><svg aria-hidden="true" className="absolute bottom-4 right-4 h-12 w-20 text-cyan-300 drop-shadow" viewBox="0 0 80 48"><path d="M5 36 C24 4 48 4 70 26" fill="none" stroke="currentColor" strokeWidth="3" /><path d="m61 23 10 3-5 9" fill="none" stroke="currentColor" strokeWidth="3" /></svg></div><p className="p-4 text-sm leading-6 text-slate-200">{shot.shotFunction}</p></button>)}</div><button type="button" disabled={isPending} onClick={() => run(() => regenerateMissingFramesAction(data.projectId, data.version.id), "Les croquis manquants ont été préparés en mode test, sans débit.")} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-2xl border border-cyan-300/50 px-5 py-4 font-black text-cyan-100"><RefreshCw size={18} /> Régénérer les croquis manquants</button></section> : null}

      <footer className="mt-8 border-t border-slate-800 pt-6"><div className="grid gap-3 sm:grid-cols-2">{data.previousSceneId ? <Link href={route(data.previousSceneId)} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-700 px-4 py-3 font-bold"><ArrowLeft size={18} /> Scène précédente</Link> : <span />}{data.nextSceneId ? <Link href={route(data.nextSceneId)} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-700 px-4 py-3 font-bold">Scène suivante <ArrowRight size={18} /></Link> : null}</div>{data.version.status === "READY" ? <button type="button" disabled={isPending} onClick={() => run(() => validateScenarioAction(data.projectId, data.version.id), "Scénario validé. Le prix du clip peut maintenant être confirmé.")} className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-cyan-300 px-6 py-5 text-lg font-black text-slate-950 disabled:opacity-50">{isPending ? <Loader2 className="animate-spin" /> : <Check />} Valider le scénario</button> : null}{data.version.status === "VALIDATED" ? <div className="mt-5 rounded-2xl border border-emerald-400/30 bg-emerald-950/25 p-5 text-center"><p className="font-black text-emerald-200">Scénario validé</p><p className="mt-2 text-sm text-slate-300">Prix du clip : {data.estimatedClipCredits.toLocaleString("fr-FR")} crédits. La création Seedance reste soumise au vrai worker et au solde disponible.</p><Link href={`/?resumeProjectId=${encodeURIComponent(data.projectId)}`} className="mt-4 inline-flex rounded-xl bg-emerald-300 px-5 py-3 font-black text-slate-950">Afficher le prix et créer avec Seedance</Link></div> : null}<div className="mt-5 flex flex-wrap justify-center gap-3 text-sm"><a href={`/api/projects/${encodeURIComponent(data.projectId)}/export?format=json`} className="underline">Télécharger JSON</a><a href={`/api/projects/${encodeURIComponent(data.projectId)}/export?format=pdf`} className="underline">Télécharger PDF</a></div></footer>
    </div>
  </div>;
}
