import os from "node:os";
import path from "node:path";
import { z } from "zod";

const positiveInt = (fallback: number) => z.coerce.number().int().positive().default(fallback);

const schema = z.object({
  DATABASE_URL: z.string().min(1),
  BLOB_READ_WRITE_TOKEN: z.preprocess((value) => value === "" ? undefined : value, z.string().min(1).optional()),
  CLOUD_STORAGE_PREFIX: z.string().regex(/^[a-zA-Z0-9/_-]+$/).default("rudyo-video-studio"),
  STORAGE_MOCK_MODE: z.enum(["true", "false"]).default("false"),
  LOCAL_STORAGE_ROOT: z.string().min(1).optional(),
  MONTAGE_WORKER_SECRET: z.string().min(32).optional(),
  WORKER_SHARED_SECRET: z.string().min(32).optional(),
  WORKER_MOCK_MODE: z.enum(["true", "false"]).default("true"),
  APP_BASE_URL: z.string().url().optional(),
  ARK_API_KEY: z.string().min(1).optional(),
  BYTEPLUS_ARK_API_KEY: z.string().min(1).optional(),
  BYTEPLUS_BASE_URL: z.string().url().default("https://ark.ap-southeast.bytepluses.com/api/v3"),
  BYTEPLUS_VIDEO_MODEL: z.literal("dreamina-seedance-2-0-260128").default("dreamina-seedance-2-0-260128"),
  BYTEPLUS_ASSET_LIBRARY_READY: z.enum(["true", "false"]).default("false"),
  BYTEPLUS_USD_PER_MILLION_TOKENS: z.coerce.number().nonnegative().default(7),
  USD_TO_EUR_RATE: z.coerce.number().positive().default(0.86),
  SEEDANCE_CONCURRENCY: positiveInt(2).pipe(z.number().max(3)),
  SEEDANCE_POLL_INTERVAL_MS: positiveInt(5000).pipe(z.number().min(1000).max(60000)),
  SEEDANCE_TASK_TIMEOUT_SECONDS: positiveInt(1800).pipe(z.number().min(60).max(7200)),
  MONTAGE_WORKER_ID: z.string().min(1).optional(),
  MONTAGE_WORKER_VERSION: z.string().min(1).default("1.0.0"),
  MONTAGE_SIGNAL_SECONDS: positiveInt(15).pipe(z.number().min(5).max(60)),
  MONTAGE_CONCURRENCY: positiveInt(1).pipe(z.number().max(8)),
  MONTAGE_MAX_ATTEMPTS: positiveInt(3).pipe(z.number().max(20)),
  MONTAGE_POLL_INTERVAL_MS: positiveInt(3000).pipe(z.number().min(250).max(60000)),
  MONTAGE_LEASE_SECONDS: positiveInt(120).pipe(z.number().min(30).max(3600)),
  MONTAGE_HEARTBEAT_SECONDS: positiveInt(30).pipe(z.number().min(5).max(300)),
  MONTAGE_MAX_INPUT_BYTES: positiveInt(1024 * 1024 * 1024),
  MONTAGE_MAX_OUTPUT_BYTES: positiveInt(2 * 1024 * 1024 * 1024),
  MONTAGE_MIN_OUTPUT_BYTES: positiveInt(1024),
  MONTAGE_MAX_DURATION_SECONDS: positiveInt(900).pipe(z.number().max(7200)),
  MONTAGE_MAX_SCENES: positiveInt(100).pipe(z.number().max(500)),
  MONTAGE_TEMP_DIR: z.string().default(path.join(os.tmpdir(), "rudyo-montage")),
  PORT: positiveInt(8080).pipe(z.number().max(65535)),
  FFMPEG_PATH: z.string().min(1).default("ffmpeg"),
  FFPROBE_PATH: z.string().min(1).default("ffprobe"),
});

const parsed = schema.superRefine((value, context) => {
  if (!value.WORKER_SHARED_SECRET && !value.MONTAGE_WORKER_SECRET) context.addIssue({ code: "custom", path: ["WORKER_SHARED_SECRET"], message: "WORKER_SHARED_SECRET is required" });
  if (value.STORAGE_MOCK_MODE !== "true" && !value.BLOB_READ_WRITE_TOKEN) context.addIssue({ code: "custom", path: ["BLOB_READ_WRITE_TOKEN"], message: "BLOB_READ_WRITE_TOKEN is required outside storage mock mode" });
}).parse(process.env);

export const config = {
  databaseUrl: parsed.DATABASE_URL,
  blobToken: parsed.BLOB_READ_WRITE_TOKEN,
  storageMockMode: parsed.STORAGE_MOCK_MODE === "true",
  localStorageRoot: path.resolve(parsed.LOCAL_STORAGE_ROOT || path.join(process.cwd(), "..", "media")),
  storagePrefix: parsed.CLOUD_STORAGE_PREFIX.replace(/^\/+|\/+$/g, ""),
  workerSecret: parsed.WORKER_SHARED_SECRET || parsed.MONTAGE_WORKER_SECRET!,
  mockMode: parsed.WORKER_MOCK_MODE === "true",
  appBaseUrl: parsed.APP_BASE_URL,
  arkApiKey: parsed.BYTEPLUS_ARK_API_KEY || parsed.ARK_API_KEY,
  bytePlusBaseUrl: parsed.BYTEPLUS_BASE_URL.replace(/\/$/, ""),
  bytePlusVideoModel: parsed.BYTEPLUS_VIDEO_MODEL,
  bytePlusAssetLibraryReady: parsed.BYTEPLUS_ASSET_LIBRARY_READY === "true",
  bytePlusUsdPerMillionTokens: parsed.BYTEPLUS_USD_PER_MILLION_TOKENS,
  usdToEurRate: parsed.USD_TO_EUR_RATE,
  seedanceConcurrency: parsed.SEEDANCE_CONCURRENCY,
  seedancePollIntervalMs: parsed.SEEDANCE_POLL_INTERVAL_MS,
  seedanceTaskTimeoutSeconds: parsed.SEEDANCE_TASK_TIMEOUT_SECONDS,
  concurrency: parsed.MONTAGE_CONCURRENCY,
  maxAttempts: parsed.MONTAGE_MAX_ATTEMPTS,
  pollIntervalMs: parsed.MONTAGE_POLL_INTERVAL_MS,
  leaseSeconds: parsed.MONTAGE_LEASE_SECONDS,
  heartbeatSeconds: parsed.MONTAGE_HEARTBEAT_SECONDS,
  maxInputBytes: parsed.MONTAGE_MAX_INPUT_BYTES,
  maxOutputBytes: parsed.MONTAGE_MAX_OUTPUT_BYTES,
  minOutputBytes: parsed.MONTAGE_MIN_OUTPUT_BYTES,
  maxDurationSeconds: parsed.MONTAGE_MAX_DURATION_SECONDS,
  maxScenes: parsed.MONTAGE_MAX_SCENES,
  tempDir: path.resolve(parsed.MONTAGE_TEMP_DIR),
  port: parsed.PORT,
  ffmpegPath: parsed.FFMPEG_PATH,
  ffprobePath: parsed.FFPROBE_PATH,
  workerId: parsed.MONTAGE_WORKER_ID || `${os.hostname()}:${process.pid}`,
  workerVersion: parsed.MONTAGE_WORKER_VERSION,
  signalSeconds: parsed.MONTAGE_SIGNAL_SECONDS,
};
