import Link from "next/link";
import {ArrowUpRight,Clapperboard,Music2,Sparkles,Layers,Check} from "lucide-react";
const uses=[{icon:Music2,title:"Clips musicaux",text:"Définissez l’ambiance, les plans et les intentions visuelles de votre chanson."},{icon:Clapperboard,title:"Vidéos promotionnelles",text:"Structurez votre message pour une offre, une association ou un événement."},{icon:Layers,title:"Formats pédagogiques",text:"Préparez un scénario clair pour expliquer, transmettre et accompagner."}];
export default function PublicHome(){return <main className="min-h-screen bg-[#070c15] text-slate-100">
<a href="#contenu" className="sr-only focus:not-sr-only focus:fixed focus:z-50 focus:bg-white focus:p-4 focus:text-black">Aller au contenu</a>
<header className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-6 py-6"><Link href="/" className="text-2xl font-black tracking-tight">Rudyo<span className="text-emerald-300">AI</span></Link><nav aria-label="Navigation principale" className="flex flex-wrap items-center gap-5 text-sm"><a href="#usages" className="text-slate-300 hover:text-white">Vos projets</a><a href="#parcours" className="text-slate-300 hover:text-white">Comment ça marche</a><Link href="/offres" className="text-slate-300 hover:text-white">Offres</Link><a href="https://app.rudyoai.com/login" className="rounded-full border border-white/20 px-4 py-2">Connexion</a></nav></header>
<section id="contenu" className="mx-auto grid max-w-7xl gap-14 px-6 py-16 lg:grid-cols-[1.1fr_0.9fr] lg:py-24"><div><p className="mb-7 inline-flex items-center gap-2 rounded-full border border-emerald-300/25 bg-emerald-300/10 px-4 py-2 text-sm text-emerald-200"><Sparkles size={16}/>Votre idée, un plan de création</p><h1 className="text-5xl font-black leading-[1.08] tracking-tight sm:text-6xl lg:text-7xl">Donnez une direction à vos <span className="text-emerald-300">vidéos.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-400">Du brief au storyboard, RudyoAI vous aide à préparer les plans et les prompts de vos clips, contenus promotionnels et capsules pédagogiques.</p><div className="mt-9 flex flex-wrap gap-4"><a href="https://app.rudyoai.com/studio" className="inline-flex items-center gap-3 rounded-full bg-emerald-300 px-6 py-4 font-bold text-slate-950 hover:bg-emerald-200">Préparer mon projet<ArrowUpRight size={19}/></a><a href="#parcours" className="rounded-full border border-white/15 px-6 py-4 font-semibold">Découvrir le parcours</a></div><p className="mt-5 text-sm text-slate-400">Le storyboard prépare votre vidéo. Le montage MP4 constitue une étape distincte.</p></div>
<div className="relative self-center rounded-3xl border border-white/10 bg-gradient-to-br from-emerald-300/10 via-slate-900 to-slate-950 p-7 shadow-2xl"><div className="mb-7 flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-widest text-emerald-200">Aperçu de storyboard</p><span className="rounded-full bg-white/5 px-3 py-1 text-xs text-slate-400">Exemple illustratif</span></div><div className="space-y-3">{[["01","Installer l’ambiance","Lumière douce · plan large"],["02","Donner du rythme","Mouvement · détail visuel"],["03","Marquer la conclusion","Message final · plan de clôture"]].map(([n,title,text])=><div key={n} className="flex items-center gap-5 rounded-2xl border border-white/10 bg-slate-950/50 p-5"><span className="text-2xl font-black text-emerald-300/70">{n}</span><div><p className="font-semibold">{title}</p><p className="mt-1 text-sm text-slate-400">{text}</p></div></div>)}</div><p className="mt-6 flex items-center gap-2 text-sm text-slate-400"><Check size={16} className="text-emerald-300"/>Plans, intentions visuelles et prompts</p></div></section>
<section id="usages" className="mx-auto max-w-7xl px-6 py-14"><p className="text-sm font-bold uppercase tracking-widest text-emerald-300">À chaque projet, son scénario</p><h2 className="mt-3 text-3xl font-bold">Créez avec une intention claire.</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{uses.map(({icon:Icon,title,text})=><article key={title} className="rounded-2xl border border-white/10 bg-white/[0.025] p-7"><Icon className="mb-6 text-emerald-300" size={28}/><h3 className="text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-400">{text}</p></article>)}</div></section>
<section id="parcours" className="mx-auto max-w-7xl px-6 py-16"><h2 className="text-3xl font-bold">Trois étapes pour avancer.</h2><ol className="mt-8 grid gap-6 md:grid-cols-3">{[["Décrivez","Choisissez votre type de vidéo, votre message, la durée et le format."],["Préparez","Générez un storyboard et des prompts, puis retrouvez les projets compatibles dans votre historique."],["Produisez","Préparez vos médias pour le montage. Sa disponibilité et son coût sont à vérifier dans le studio."]].map(([title,text],i)=><li key={title} className="border-t border-white/15 pt-5"><span className="text-sm text-emerald-300">0{i+1}</span><h3 className="my-3 text-xl font-bold">{title}</h3><p className="leading-7 text-slate-400">{text}</p></li>)}</ol></section>
<section className="mx-auto max-w-7xl px-6 py-12"><div className="rounded-3xl border border-emerald-300/20 bg-emerald-300/5 p-8 sm:p-12"><h2 className="text-3xl font-bold">Commencez par votre idée.</h2><p className="my-5 text-slate-400">Le coût du storyboard est affiché avant confirmation dans le studio.</p><a href="https://app.rudyoai.com/studio" className="inline-flex items-center gap-2 rounded-full bg-emerald-300 px-6 py-3 font-bold text-slate-950">Ouvrir le studio<ArrowUpRight size={18}/></a></div></section>
<footer className="mx-auto flex max-w-7xl flex-wrap justify-between gap-4 border-t border-white/10 px-6 py-8 text-sm text-slate-400"><p>RudyoAI · Farozik production</p><a href="https://app.rudyoai.com/login" className="hover:text-white">Accéder à mon espace</a></footer>
</main>}
