ALTER TYPE "GenerationTaskStatus" ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE "GenerationTaskStatus" ADD VALUE IF NOT EXISTS 'SUBMITTED';
ALTER TYPE "GenerationTaskStatus" ADD VALUE IF NOT EXISTS 'PROCESSING';
ALTER TYPE "GenerationTaskStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE "GenerationTaskStatus" ADD VALUE IF NOT EXISTS 'REFUNDED';
