ALTER TYPE "VideoProjectStatus" ADD VALUE IF NOT EXISTS 'GENERATING';

ALTER TABLE "VideoProject"
  ADD COLUMN IF NOT EXISTS "creditReservationId" TEXT,
  ADD COLUMN IF NOT EXISTS "audioStartSeconds" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "billedDurationSeconds" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "clientRevenueEur" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "estimatedProviderCostEur" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "actualProviderCostEur" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "estimatedMarginEur" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "actualMarginEur" DOUBLE PRECISION;

CREATE UNIQUE INDEX IF NOT EXISTS "VideoProject_creditReservationId_key" ON "VideoProject"("creditReservationId");
